# For creating stack 'haproxy' on a dedicated node tagged 'infra'
haproxy:
  image: 'dockercloud/haproxy:latest'
  links:
    - 'api.api:api'
    - 'api-dev.api-dev:api-dev'
  ports:
    - '80:80'
  restart: always
  roles:
    - global
  tags:
    - infra
