postgres-dev:
  image: sameersbn/postgresql:9.5-2
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_PASSWORD=admin
    - DB_USER=example
    - DB_PASS=admin
    - DB_NAME=example  # , table2
  #   - PGDATA=/pgdata
  # volumes:
  #   - ./db/pgdata:/pgdata
  #   - ./db/sample-setup.sql:/docker-entrypoint-initdb.d/sample-setup.sql
